dist: bionic
language: bash
arch:
  - amd64
  - arm64

services:
  - docker

script:
  - VERSION := $(bash 'cat VERSION')
  - make docker
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - VERSION := $(bash 'cat VERSION')
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
       docker tag abhishek138/fluentd-hec:$(VERSION) abhishek138/fluentd-hec:$(VERSION)_arm64;
       docker push abhishek138/fluentd-hec:$(VERSION)_arm64;
    else
       docker push abhishek138/fluentd-hec:$(VERSION);
    fi
  #- docker build --no-cache --pull --build-arg VERSION=$(VERSION) --build-arg NODEJS_VERSION=$(NODEJS_VERSION) -t splunk/fluentd-hec:$(VERSION) ./docker
  #- docker buildx build --platform linux/amd64,linux/arm64 -t abhishek138/team:latest -f ./docker/Dockerfile -t abhishek138/team:latest -f ./docker/Dockerfile --push .;
